### ISSUE TITLE
Bookmarks path cause setup failed on Windows

### ISSUE THREAD

**Issue by ErogeMaster225** [ldelossa/nvim-ide#22]
The line below assume the user's operating  system is Linux and will cause issues on Windows system because the default Neovim config folder path on Windows is different from Linux
https://github.com/ldelossa/nvim-ide/blob/e81fbd084f10b92bb6a4f62155e0fa1edbee9c7e/lua/ide/components/bookmarks/component.lua#L13
Maybe you should use stdpath function to get the config folder instead

**Comment by ldelossa** [comment]
Hey there, 

I am not a Windows user, so I'm going to lean on Windows users to fish out these issues and fix them. I will mark them as "help wanted".

**Comment by ErogeMaster225** [comment]
Sorry for late reply, about this issue i think 
`BookmarksComponent.NotebooksPath = vim.fn.stdpath "config" .. "/bookmarks"`
 should works on all platforms

**Comment by ldelossa** [comment]
Fixed via contribution

**Comment by ldelossa** [comment]
@ErogeMaster225 @VidocqH 

I just want to give you guys a heads up. 

I am changing the encoding of notebook and bookmark files to `base64`  instead of sha256 so the strings can also be decoded. 

This will ultimately allow for migration of bookmarks to a renamed repository, and a renamed file, if this occurs. 

However, this will break existing bookmarks. 

Since nvim-ide is so new, I do not want to put the sha256->base64 checks and conversions into the plugins. So expect any existing bookmarks and notesbooks to fail.

This should be the last time we have to deal with this intterupt.
