### ISSUE TITLE
When selecting a file from the file tree or bufferlist components, allow the user to select a window instead of just choosing the most recent window

### ISSUE THREAD

**Issue by mrjones2014** [ldelossa/nvim-ide#61]
with `nvim-tree` when you select a file, it uses the statusline/winbar to set a label (`A`/`B`/`C` etc) on each window, and pressing the key corresponding to each window opens the file in that window.

It would be cool to do something similar with `nvim-ide`

**Comment by ldelossa** [comment]
TBH, instead of re-implementing all the features ppl miss from nvim-tree, I was really curious if its actually possible write some type of bridging lua module which makes `nvim-tree` a `nvim-ide` component. 

We'd basically need to manage just the nvim-tree buffer, and take over the window creation, and them give the window ID back to nvim-tree so it can do anything window related with the Panel's window.

**Comment by mrjones2014** [comment]
It might be possible, it would depend on how nvim-tree renders its window/buffer internally. We can look into it.
